<?php

/**
 * Implementation of hook_permission().
 */
function mysearch_permission() {
  return array(
    'access mysearch' => array(
      'title' => 'Access My Search',
      'description' => 'Allows a user to access search results',
    )
  );
}


/**
 * Implementation of hook_menu().
 */
function mysearch_menu() {
  $items['mysearch'] = array(
    'title' => 'Search',
    'page callback' => 'mysearch_searchpage',
    'access arguments' => array('access mysearch'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Menu callback provides a simple list of nodes matching the
 * search term Example: hitting the URL:
 *   http://domain.com/mysearch/example
 * will return a list of links to nodes which have the word
 * example in them.
 */
function mysearch_searchpage() {
  $searchterm = arg(1);
  drupal_set_title('Search results for ' . $searchterm);
  $query = "SELECT entity_id AS nid FROM {field_data_body} WHERE body_value LIKE :searchterm";
  $args = array(':searchterm' => '%' . db_like($searchterm) . '%');
  $nids = db_query($query, $args)->fetchAllKeyed(0, 0);
  $nids = array_values($nids);
  $nodes = node_load_multiple($nids);
  $items = array();
  foreach($nodes as $node) {
    $items[] = l($node->title, 'node/' . $node->nid);
  }
  $title = format_plural(count($items), 'Found 1 result containing the words: ', 'Found @count results containing the words: ') . '<strong>' . $searchterm . '</strong>';
  $output = theme('item_list', array('items' => $items, 'title' => $title));
  return $output;
}